name: ServerSigns
main: de.czymm.serversigns.ServerSignsPlugin
version: ${version}
api-version: 1.13
authors: [CalibeR50, Exloki]
softdepend: [Vault, NoCheatPlus, Essentials, PlaceholderAPI]
load: POSTWORLD
description: >
             ServerSigns
commands:

  serversigns:
    description: The main ServerSigns plugin command
    aliases: svs
    usage: /<command>

  serversignsremote:
    description: Allows remote modification of ServerSigns
    aliases: svsr
    usage: /<command>

permissions:

    serversigns.admin:
        description: Gives access to all ServerSigns commands
        default: op
        children:
          serversigns.command.add: true
          serversigns.command.set_cancel: true
          serversigns.command.cancel_permission: true
          serversigns.command.confirmation: true
          serversigns.command.copy: true
          serversigns.command.create: true
          serversigns.command.edit: true
          serversigns.command.grant: true
          serversigns.command.held_item_criteria: true
          serversigns.command.holding: true
          serversigns.command.import: true
          serversigns.command.insert: true
          serversigns.command.list: true
          serversigns.command.long: true
          serversigns.command.option: true
          serversigns.command.price_item: true
          serversigns.command.price_item_criteria: true
          serversigns.command.reload: true
          serversigns.command.reload_config: true
          serversigns.command.reload_signs: true
          serversigns.command.remove: true
          serversigns.command.reset_all_cooldowns: true
          serversigns.command.reset_cooldown: true
          serversigns.command.resetcooldowns: true
          serversigns.command.select: true
          serversigns.command.set_cooldown: true
          serversigns.command.set_global_cooldown: true
          serversigns.command.set_loops: true
          serversigns.command.set_permission: true
          serversigns.command.set_price: true
          serversigns.command.set_uses: true
          serversigns.command.silent: true
          serversigns.command.timelimit: true
          serversigns.command.void: true
          serversigns.command.xp: true

    serversigns.use:
        description: Allows you to use a ServerSign

    serversigns.updatenotification:
        default: op
        description: Allows you to see update notifications